katze_sources = files(
  'app.cpp',
  'Dctx.cpp',
  'draw.cpp',
  'Font.cpp',
  'icons.cpp',
  'Renderer.cpp',
  'Root.cpp',
  'Window.cpp',
  'input/Cursor.cpp',
  'input/mouse.cpp',
  'widgets/Box.cpp',
  'widgets/Button.cpp',
  'widgets/Capsule.cpp',
  'widgets/Checkbox.cpp',
  'widgets/Icon.cpp',
  'widgets/IconLabel.cpp',
  'widgets/Label.cpp',
  'widgets/Padding.cpp',
  'widgets/Reactive.cpp',
  'widgets/Rectangle.cpp',
  'widgets/Slider.cpp',
  'widgets/Spacer.cpp',
  'widgets/Widget.cpp',
)
